services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:42
    networks:
      - inception
    restart: always
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ../home/jimpark/data/mariadb
      o: bind