services:
  nginx:
    build: ./requirements/nginx
    image: nginx:42
    networks:
      - inception
    restart: always
    ports:
      - 443:443
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:42
    networks:
      - inception
    restart: always
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/jimpark/Desktop/42seoul/inception/home/jimpark/data/mariadb
      o: bind